### ISSUE TITLE
Model Djangowy - użytkownik

### ISSUE THREAD

**Issue by DamianKobylinski** [knmlprz/My_browarek#14]
**Model Użytkownika**

---
Zadania:
- Inicjalizacje modelu wraz z odpowiednimi kolumnami
- Serializers 
- Wrzucenie Formularza Modelu do wglądu z widoku administratora 
- Podpięcie pod swagger'a

**Comment by FWalkowicz** [comment]
### 13.04 - @SINEdowskY  @FWalkowicz @DamSte09 
Praca wspólna nad modelem User'a

### Rzeczy zrobione

 - Profil użytkownika:
   - user - django.contrib.auth.models.User
   - weight - waga Float z ograniczeniami 
   - height - wzrost z ograniczeniami
   - birthDate - data urodzenia z walidacją użytkownika powyżej 18 raku życia
 - Rejestracja modelu w admin
 - Rejestracja aplikacji w settings.py
 - Zrobienie i wykonanie migracji
 
### Problemy
 
 - Błąd z walidatorem daty urodzenia - niepoprawne operacje na datach

### Podział na kolejne taski

 - @DamSte09 - serializers 
 - @SINEdowskY - poprawa błędu z datą, testy, podpięcie pod swaggera
 - @FWalkowicz - formularza modelu, docstring

**Comment by jakubgolen** [comment]
### 13.04 - @SINEdowskY

### Rzeczy zrobione
Profil użytkownika:
 - poprawa błędu z walidatorem daty urodzenia
### Problemy
 - brak

**Comment by jakubgolen** [comment]
### 14.04 - @SINEdowskY

### Rzeczy zrobione
Profil użytkownika:
 - Testy jednostkowe do modelu profilu użytkownika
### Problemy
 - Dla weight i height przechodzą wartości 0

**Comment by FWalkowicz** [comment]
14.04 - @FWalkowicz 
### Rzeczy zrobione

 - dodanie docstring'ów 
 - utworzenie formularza dla `UserProfile`
 - rejestracja formularza w panelu admina

### Problemy

Poprawne wyświetlanie tabeli `UserProfile` w widoku administratora, nie wyświetlają się wszystkie pola.


![Image](https://github.com/knmlprz/My_browarek/assets/32652664/fc105848-3daf-4cb9-b7df-f3119f5cfe50)

**Comment by FWalkowicz** [comment]
> ### 14.04 - [@SINEdowskY](https://github.com/SINEdowskY)
> ### Rzeczy zrobione
> 
> Profil użytkownika:
> 
>     * Testy jednostkowe do modelu profilu użytkownika
> 
> 
> ### Problemy
> 
>     * Dla weight i height przechodzą wartości 0

@SINEdowskY 
Próbowałeś może w walidatorach ustawić 1 zamiast 0:
```python
validators.MinValueValidator(0) -> validators.MinValueValidator(1)
```

**Comment by DamSte09** [comment]
15.04 - @DamSte09 

### Rzeczy zrobione
 - zapoznanie się z dokumentacją i strukturą serializera 

### Problemy/zapytania
 - problem ze zrozumieniem serializacji OneToOneField

**Comment by DamSte09** [comment]
15.04 - @DamSte09 

### Rzeczy zrobione
 - Dodanie serializera dla UserProfile

**Comment by jakubgolen** [comment]
23.04 - @SINEdowskY

### Rzeczy zrobione
- Dodanie customowej metody `create` do Serializera dla `UserProfile` (`ModelViewSet` bazowo nie ogarnia nestowanych pól JSONa)
- Napisanie podstawowego viewseta do profili (`UserProfileViewSet`)
- Podpięcie do routera i swaggera
- testowanie manualne endpointów
### Problemy
 - Musiałem na chwilę usunąć pole `groups` z serializera użytkownika (`UserSerializer`) ze względu na problemy z hiperłączami (?) (Nie jestem pewien, ale chyba wymaga to endpointu do grup) jest to pole opcjonalne więc póki co nie jest potrzebne i nie wpływa na działanie aplikacji.
 - `UserProfileForm` nie ogarnia edycji już dodanych profili za pomocą API (Nie wiem czy to błąd dodaję taką informację.)
 
![image](https://github.com/knmlprz/My_browarek/assets/26627330/8689eeef-a6ab-4c37-b99b-f73d8f5375d4)

### Testy
#### Test POST
![image](https://github.com/knmlprz/My_browarek/assets/26627330/665c0d59-42f1-4e7b-9312-1c52f3458325)

#### Test GET
![image](https://github.com/knmlprz/My_browarek/assets/26627330/15533254-1e40-41b4-907c-77607dac4a82)

**Comment by DamianKobylinski** [comment]
Merged to backend/stable - everything is fine
