### ISSUE TITLE
Model Djangowy - zbiór piwa

### ISSUE THREAD

**Issue by DamianKobylinski** [knmlprz/My_browarek#15]
**Model Zbioru piwa**

---
Zadania:
- Inicjalizacje modelu wraz z odpowiednimi kolumnami 
- Serializers
- Wrzucenie Formularza Modelu do wglądu z widoku administratora 
- Podpięcie pod swagger'a

**Comment by DamianKobylinski** [comment]
Podział tasku:
Jakub i Przemek:
  - Stworzenie modelu widocznego dla widoku administratora, model posiada takie kolumny jak:
       - nazwa piwa
       - opis piwa 
       - ścieżka do obrazu piwa

Damian:
  - Znalezienie zbioru danych w postaci API, podpięcie MyBrowarek do API

Deadline na wysłanie informacji jak z subtaskiem idzie : 16.04.2024r.

**Comment by MrKamirus** [comment]
Stworzyliśmy model beer z kolumnami: 
 - nazwa
 - opis 
 - ściezke do obrazu URL 

Dodaliśmy go do panelu administracyjnego i działa - nie dodaliśmy go jeszcze na gita

**Comment by DamianKobylinski** [comment]
Branch with Beer Model integrated with swagger, PR created - #22 



![Image](https://github.com/knmlprz/My_browarek/assets/20757441/282b8dc8-d7a4-492f-a065-6cd596a6c507)
