### ISSUE TITLE
Design widoku piwa

### ISSUE THREAD

**Issue by Kleczyk** [knmlprz/My_browarek#23]
# Opis

Stworzenie mockupu dla widoku piwa gdzie będzie widoczne obraz piwa, ocena, opis, cechy(goryczka moc itp.)

# Zadania

- [ ] zdj piwa

- [ ] opis

- [ ] cechy 

- [ ] ocena

- [ ] wybór kolorów

# Jak Może wyglądać rozwiązanie 

Mockaupy w figmie 

# Co blokuje 
-

**Comment by kosiarn** [comment]
Makieta widoku piwa ukończona; znajduje się w projekcie teamu na Figmie.
