### ISSUE TITLE
Konfiguracja Repozytorium 

### ISSUE THREAD

**Issue by Kleczyk** [knmlprz/My_browarek#7]
# Opis

Konfiguracja repozytrium ma na celu poprawienie całego work flow projktu tak aby wyeliminować zagrożenia i zrobić je jak najbardziej przejrzyste

# Zadanie

- [x] Stworzenie innych branchy

- [x] Zabezpieczenie innych branchy

- [x] dodanie templatów do issue i PR

- [x] dodanie labelów do repo

# Jak Może wyglądać rozwiązanie 

Templaty  dla PR oraz issue aby dobrze dokładnie opisywać co wprowadzamy, zabezpiesznie branchy tak aby nie wprowadzić zmian nie sprawdzonych smian 

# Co blokuje 
-

**Comment by Kleczyk** [comment]
Repo zostałow wstępnie skonfigurowane można zabczyć 
- czy tamplaty są ok 
- czy branche są ok  musiałem stworzyć np beckend/stable ponieważ nie można uwtwożyć samego beckend  a potem robić branche beckend/<nazwa nowej kategorii branchy > #8 
- główne branche są zabezpieczne w takie sposób aby nie dało się na nie pushować commitów tylko  trzeba robić PR a poetem Margeować

**Comment by kosiarn** [comment]
@knmlprz/my_browarek review! kto pierwszy ten lepszy

**Comment by Kleczyk** [comment]
@kosiarn @DamianKobylinski  dodajcie to ustawienie aby losowało  osobę z waszego teamu do code review  bo ja to mogę zrobić ale dla całego teamu  My_browarek 

![Image](https://github.com/knmlprz/My_browarek/assets/101070249/f6c4584a-164e-4524-b09a-635e3fffd4ec)
