### ISSUE TITLE
Opracowanie git flow

### ISSUE THREAD

**Issue by Kleczyk** [knmlprz/My_browarek#8]
# Ustalenia dotyczące Git flow

### Główne branche
- ```main``` - głowna gałąź repozytorium, aplikacja znajdująca się w danym miejscu uznawana jest za wersje stabilną, możliwą do wrzucenia na servery live (mr do brancha ```deploy```)
- ```deploy``` - gałąź cechująca wersje wrzuconą na servery live

### Branche frontendowe 

- frontend/... - gałąź wyznaczająca stabilną wersje frontendu aplikacji
- frontend/feature/... - gałąź wszelkich zmian po stronie frontendu
- frontend/bug/... - gałąź, która prezentuje błąd w kodzie uniemożliwiająca dalszy rozwój aplikacji/ przedstawiająca różnego rodzaju błędy i niestabilne działanie
- frontend/test/... - gałąź cechująca się testem danej funkcjonalności po stronie frontendu

### Branche backendowe 

- backend/... - gałąź wyznaczająca stabilną wersje backendu aplikacji
- backend/feature/... - gałąź wszelkich zmian po stronie backendu
- backend/bug/... - gałąź, która prezentuje błąd w kodzie uniemożliwiająca dalszy rozwój aplikacji/ przedstawiająca różnego rodzaju błędy i niestabilne działanie
- backend/test/... - gałąź cechująca się testem danej funkcjonalności po stronie backendu

Powyższe założenia zostały przyjęte na spotkania całego zespołu (27.03.2024)

**Comment by DamianKobylinski** [comment]
Głowne Brancha:
- main
- deploy

Frontend Branch
- frontend/....
- frontend/feature/....
- frontend/bug/.....
- frontend/test/.....

Backend Branch 
- backend/....
- backend/feature/....
- backend/bug/......
- backend/test/.....
