### ISSUE TITLE
Tworzenie user flow

### ISSUE THREAD

**Issue by Kleczyk** [knmlprz/My_browarek#9]
# Opis

Pierwszym krokiem stworzenia interfejsu jest zaprojektowanie go. Zacznijmy od jasno określonego user flow.

# Zadanie

Zaprojektuj pełny szkic user flow aplikacji. Uwzględnij interakcje z każdym możliwym interaktywnym elementem i efekt tej interakcji jako przejście do innego widoku.

# Jak Może wyglądać rozwiązanie 

Pełny szkic user flow w dowolnym formacie zapisanym elektronicznie - wliczają się w to również zdjęcia szkicu wykonanego na papierze.

# Co blokuje 
-

**Comment by kosiarn** [comment]
Szkic by @FWalkowicz 
![image](https://github.com/knmlprz/My_browarek/assets/62908964/dfd92980-c57f-406b-ab37-7051784ade99)

@Kleczyk team frontendowy prosi o przejrzenie szkicu MVP (ścieżki 1 i 4); głównie danych do rejestracji:
- Czy tych danych będziemy wymagać od użytkownika?
- Czy będziemy wymagać dodatkowego kroku przy rejestracji, na przykład potwierdzenia maila?

**Comment by kosiarn** [comment]
@Kleczyk zatwierdził szkic; zamykam.
